### ISSUE TITLE
RuntimeError: table 'taz_control_data' never checkpointed. Closing remaining open files:output\pipeline.h5...done

### ISSUE THREAD

**Issue by issa-jtmt** [ActivitySim/populationsim#116] opened 2020-03-15 20:26 UTC
Dear All,

I am trying to run the popsim, and it seems all is working till one I get this message after the run_pop reads the files:

RuntimeError: table 'taz_control_data' never checkpointed.
Closing remaining open files:output\pipeline.h5...done

Any help?

Regards,

Issa

**Comment by bettinardi** [comment] 2020-03-16 16:06
That sounds like it is failing pretty early.  It seems like the taz data control is not established correctly.  How may minutes or seconds would you say that it ran before it got to this message?

**Comment by toliwaga** [comment] 2020-03-16 17:50
the log file would be helpful

**Comment by issa-jtmt** [comment] 2020-03-16 21:26
[activitysim.log](https://github.com/ActivitySim/populationsim/files/4340487/activitysim.log)
Please note that it takes me less than 30 seconds to have this message. I could not understand the problem there.

Any help would do.

thanks.

Issa

**Comment by bettinardi** [comment] 2020-03-16 21:31
I'll leave it to Jeff to provide a more helpful response, but it looks like it read the control_taz.csv file fine, so I'm guessing there must be an inconsistency in the settings.ymal or  controls.csv.  Either that or it could be a data type in the control_taz file.  In other issues we have found that PopulationSim doesn't do well with decimals in the control input files.  You might ensure that everything is a round integer in your taz file and all your control files.

**Comment by issa-jtmt** [comment] 2020-03-16 21:31
By the way, I am very desperate and disappointed by this error message, which does not have a clear meaning. I tried everything, still to no avail. Any help would be really appreciated.

I attached also the yaml file (in text here).

Issa
[‏‏settings.txt](https://github.com/ActivitySim/populationsim/files/4340507/settings.txt)

**Comment by bettinardi** [comment] 2020-03-16 21:37
I would echo that PopulationSim would benefit from better error reporting in general, and one thing that would help that would be some standard checks up front for known issues so that those issues can be flagged and a more helpful error message can be provided.  I see that taz is your lowest level of geography.  That means that num_hh specifically needs to be called out and pointed to the correct field in your controls.csv.  Again, I would check for and round off any decimals.  Ensure all control files are integer only...

**Comment by issa-jtmt** [comment] 2020-03-16 21:38
Well, I  do not have any kind of decimals in the control file. This is not the issue here. 
Al the data types there are numerical. No letters or anything. I will post also controls and the geo_cross_walk files (moved them to text).

Thanks.

[‏‏geo_cross_walk.txt](https://github.com/ActivitySim/populationsim/files/4340524/geo_cross_walk.txt)
[‏‏control_taz.txt](https://github.com/ActivitySim/populationsim/files/4340525/control_taz.txt)

**Comment by bettinardi** [comment] 2020-03-16 21:43
The other file that would need to be shared is the controls.csv in the config folder

**Comment by issa-jtmt** [comment] 2020-03-16 21:45
[‏‏controls.txt](https://github.com/ActivitySim/populationsim/files/4340547/controls.txt)
Attached.

Sorry for the mess, but I need to run this ASAP.

**Comment by bettinardi** [comment] 2020-03-16 21:52
I don't know how the seed was processed.  It looks like in your control file you are referencing a "hhnum" filed in your seed.  I know we have had issues when we try and mess with the expression for "num_hh".  You have this - households.hhnum > 0

We have this:
(households.WGTP > 0) & (households.WGTP < np.inf)

I'll let you know if I think of anything else, but that's currently my best thought.  Maybe Jeff or others can review and provide better instruction.

I would add that after you get this working, you are going to have conflicting controls.  All your size controls are going to fight directly with your duplicate population control - 
population,taz,persons,1000000,pop,persons.hhnum >= 1

I don't think that population control will work as intended.  I suggest removing that one, and letting the population by age controls do the work of that total population control.

Related to this, you might consider doing tests where you start with a smaller set of controls and then add controls and see how those impact the results (once you get it working).

**Comment by binnympaul** [comment] 2020-03-17 02:52
Here is the original runtime error

![image](https://user-images.githubusercontent.com/16109140/76817048-13fd4000-67bf-11ea-9c39-339e18cd5188.png)

Just reiterating what I sent in the email for better documentation.

PopulationSim expects you to be consistent with geography names, it is even case sensitive. In your settings file, where you list the geographies, “taz” is in lower case but while defining the taz control table, you use uppercase. 

  - tablename: **TAZ**_control_data
    filename : control_taz.csv

Please update this thread if that fixes it.

**Comment by binnympaul** [comment] 2020-03-17 13:39
@issa-jtmt : Since this has been resolved can we please close this issue? I will open another issue with an enhancement/documentation tag

**Comment by issa-jtmt** [comment] 2020-03-17 13:57
Yes, all is fine.

**Closed** 2020-03-17 21:28 UTC
